repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.368
    hooks:
    - id: pyright
